if(EXISTS "/disk/moose/general/djdt/lhcbUII_masters/DetectorPlayground/Detector/build.x86_64_v2-el9-gcc12-opt/Detector/Muon/tests/muon_tests_tests-b12d07c.cmake")
  include("/disk/moose/general/djdt/lhcbUII_masters/DetectorPlayground/Detector/build.x86_64_v2-el9-gcc12-opt/Detector/Muon/tests/muon_tests_tests-b12d07c.cmake")
else()
  add_test(muon_tests_NOT_BUILT-b12d07c muon_tests_NOT_BUILT-b12d07c)
endif()
